# Basic Information 
title: Donya Rooein
position: Postdoctoral Fellow
affiliation: Bocconi University
affiliation_link: https://www.unibocconi.it/
email: donyarooein (at) unibocconi.it

# Search Engine Optimization (SEO)
keywords: donya rooein, donyarooein, rooeindonya, donyarooein
canonical: https://milanlproc.github.io/authors/donya_rooein/
description: Donya Rooein is a postdoctoral fellow at Bocconi University. Her research lies in NLP, Conversational AI, and Applied ML.

# The option is used to enable the Johns Hopkins template.
enable_jhu_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=1iRLeoMAAAAJ&hl=en
cv_link: files/donya-rooein-cv.pdf
github_link: https://github.com/donya-rooein/
linkedin: https://www.linkedin.com/in/donya-rooein/
twitter: https://twitter.com/donyarooein/

# Images 
avatar: files/donya-rooein-avatar.JPG
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
